version: "3.9"

services:

  zabbix-mariadb:
    image: mariadb:11.2
    container_name: zabbix-mariadb
    hostname: zabbix-mariadb
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpass
    networks:
      - default
    volumes:
      - /srv/mariadb/data:/var/lib/mysql

  zabbix-server:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix-server
    hostname: zabbix-server
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
      DB_SERVER_HOST: zabbix-mariadb
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpass
    networks:
      default:
        ipv4_address: 172.29.0.254
    depends_on:
      - zabbix-mariadb

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql
    container_name: zabbix-web
    hostname: zabbix-web
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
      DB_SERVER_HOST: zabbix-mariadb
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpass
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: "Europe/Moscow"
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - default
    depends_on:
      - zabbix-mariadb
      - zabbix-server

  zabbix-agent:
    image: zabbix/zabbix-agent
    container_name: zabbix-agent
    hostname: zabbix-server
    restart: unless-stopped
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_LOGREMOTECOMMANDS: 0
      ZBX_BUFFERSIZE: 100
    ports:
      - 10050:10050
    networks:
      - default
    labels:
      com.zabbix.description: "Zabbix agent"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-agentd"
      com.zabbix.os: "alpine"
    depends_on:
      - zabbix-server

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
